name: NewBackup
on:
  workflow_dispatch:
jobs:
  run-task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Run
        run: node index.js
      - name: Save
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "bot"
          git add .
          git commit -m "update data" || exit 0
          git push
